### ISSUE TITLE
Networkx version & What is MCS-DR & How to use networkx graph as input to calculate MCS

### ISSUE THREAD

**Issue by nightlyjourney** [mojaie/chorus#4]
Could you please tell me what the version of networkx you are using?

**Comment by mojaie** [comment]
I'm using version 2.1 in my development environment.
Maybe 2.0 or higher can be used.

**Comment by NightlyJourney** [comment]
Thanks for your reply. It would be nice if you could provide a paper link about the algorithm you used. I am a little bit confused about the parameter 'diameter'.

Also, I am confused about the 'type' attribute in 'Bond' class, does it represent valence? Cause I try to use it to represent valence, and it appears the mcs result is not correct.

Thanks a lot.

**Comment by nightlyjourney** [comment]
Thanks for your reply. It would be nice if you could provide a paper link about the algorithm you used. I am a little bit confused about the parameter 'diameter'.

Also, I am confused about the 'type' attribute in 'Bond' class, does it represent valence? Cause I try to use it to represent valence, and it appears that the mcs result is not correct.

Thanks a lot.

**Comment by mojaie** [comment]
MCS-DR/GLS is a MCS derivative that is designed for network-based SAR analysis. The paper is in preparation and there is only a proceeding for a domestic conference (in Japanese).
https://www.jstage.jst.go.jp/article/ciqs/2017/0/2017_P4/_article
I will add some documentation of the algorithm soon.

MCS-DR size is typically smaller than exact MCS size because bond distance descriptors is adopted to reduce the computation cost. See following paper for more information.
Sheridan, R. P.; Miller, M. D. J. Chem. Inf. Comput. Sci. 1998, 38, 915 924.

Bond.type and Bond.order indicates its appearance (solid line, allow, doubled line, or etc.) and mainly used for chemical structure drawing. Bond order information used for the analysis is stored in Atom.pi as a number of pi electrons.

Thank you very much for your interest in this library.

**Comment by nightlyjourney** [comment]
Thank you so much for your timely reply, but I still have problem with using chorus:

The dataset I use only contain the information of atom type (e.g. Carbon, Hydrogen etc.) and bond valence, which is a number, normally 1 or 2 (e.g. C-C is 1, C=O is 2 etc.). I store the graph of a compound as a networkx graph, here is the code I tried to use chorus to calculate MCS

```python
from chorus.model.graphmol import Compound
from chorus.mcsdr import from_array,comparison_array
from chorus.model.atom import Atom
from chorus.model.bond import Bond
import networkx as nx

g1 = nx.read_gexf('temp_1.gexf')
g2 = nx.read_gexf('temp_2.gexf')

c1 = Compound()
c2 = Compound()

for node in g1.nodes():
   c1.add_atom(node,Atom(g1.node[node]['type']))
for edge in g1.edges():
   c1.add_bond(edge[0],edge[1],Bond({"type":g1[edge[0]][edge[1]]['valence']}))
for node in g2.nodes():
   c2.add_atom(node,Atom(g2.node[node]['type']))
for edge in g2.edges():
   c2.add_bond(edge[0],edge[1],Bond({"type":g2[edge[0]][edge[1]]['valence']}))
c1.descriptors = set(["Valence"])
c2.descriptors = set(["Valence"])

a1 = comparison_array(c1,ignore_hydrogen=False)
a2 = comparison_array(c2,ignore_hydrogen=False)

g = from_array(a1,a2)
print(str(g.edge_count()))
``` 
As you can see, in networkx graph, I use node attribute 'type' to store the atom type information and use edge attribute 'valence' to store the bond valence  information.

I have attached two gexf files for your reference. As I see, the MCS between them should be 3 while the result calculated by chorus is 6. Could you please help me fix this issue? Thanks a lot.
[gexf_files.zip](https://github.com/mojaie/chorus/files/2052609/gexf_files.zip)

**Comment by mojaie** [comment]
chorus.descriptor.assign_valence converts bond order into Atom.pi.

```py
from chorus.model.atom import Atom
from chorus.model.bond import Bond
from chorus import descriptor
import networkx as nx

g1 = nx.read_gexf('temp_1.gexf')

c1 = Compound()

for node in g1.nodes():
    c1.add_atom(Atom(node))  # atom symbol text in str (ex. 'C')
for edge in g1.edges():
    b = Bond()
    b.order = int(g1[edge[0]][edge[1]]['valence'])  # bond order value in int
    c1.add_bond(b)
print("Valence" in c1.descriptors)  # False

descriptor.assign_valence(c1)  # MCS-DR requires precalculated "Valence" information
print("Valence" in c1.descriptors)  # True

print(c1)  # This will give a simple summary of the molecular graph
```

**Comment by nightlyjourney** [comment]
Thank you so much for your help. I modified the code as follows based on your tip, but the problem is still there.

```python
from chorus.model.graphmol import Compound
from chorus.mcsdr import from_array,comparison_array
from chorus.model.atom import Atom
from chorus.model.bond import Bond
from chorus import descriptor
import networkx as nx

g1 = nx.read_gexf('temp_1.gexf')
g2 = nx.read_gexf('temp_2.gexf')

c1 = Compound()
c2 = Compound()

for node in g1.nodes():
    c1.add_atom(Atom(node))
for edge in g1.edges():
    b = bond
    b.order = int(g1[edge[0]][edge[1]]['valence'])
    c1.add_bond(b)
for node in g2.nodes():
    c2.add_atom(Atom(node))
for edge in g2.edges():
    b = bond
    b.order = int(g2[edge[0]][edge[1]]['valence'])
    c2.add_bond(b)

descriptor.assign_valence(c1)
descriptor.assign_valence(c2)

a1 = comparison_array(c1,ignore_hydrogen=False)
a2 = comparison_array(c2,ignore_hydrogen=False)

g = from_array(a1,a2)

print('MCS calculation: {}'.format(str(g.edge_count())))
```

The result is still 6 instead of 3, and an error showed up as follows:
```
Traceback (most recent call last):
  File "mcs_cal.py", line 18, in <module>
    c1.add_atom(Atom(node))
  File "/Users/nightlyjourney/anaconda3/envs/***/lib/python3.6/site-packages/Chorus-0.8.0-py3.6-macosx-10.7-x86_64.egg/chorus/model/atom.py", line 69, in __init__
    self.name = P_TAB[symbol]['name']
KeyError: '0'
MCS calculation: 6
```

Could you please give me some suggestions to fix it? Thanks a lot.

**Comment by mojaie** [comment]
```py
c1.add_atom(Atom(node))  # atom symbol text in str (ex. 'C')
```
Here, `node` should be an atom symbol (Is it stored in  `g1.node[node]['type']` ?)
Can you show me `print(c1)` output as the last line of my example code?
And how did you catch KeyError? Incomplete molecular model will result unexpected results.

**Comment by nightlyjourney** [comment]
Thank you so much for your kind help, and truly sorry for my late reply, I changed the code based on your advice as follows and it works now :)
```python
from chorus.model.graphmol import Compound
from chorus.mcsdr import from_array,comparison_array
from chorus.model.atom import Atom
from chorus.model.bond import Bond
from chorus import descriptor
import networkx as nx

g1 = nx.read_gexf('temp_1.gexf')
g2 = nx.read_gexf('temp_2.gexf')

c1 = Compound()
c2 = Compound()

for node in g1.nodes():
    c1.add_atom(node, Atom(g1.node[node]['type']))
for edge in g1.edges():
    b = Bond()
    b.order = int(g1[edge[0]][edge[1]]['valence'])
    c1.add_bond(edge[0],edge[1],b)
for node in g2.nodes():
    c2.add_atom(node, Atom(g2.node[node]['type']))
for edge in g2.edges():
    b = Bond()
    b.order = int(g2[edge[0]][edge[1]]['valence'])
    c2.add_bond(edge[0],edge[1],b)

descriptor.assign_valence(c1)
descriptor.assign_valence(c2)

a1 = comparison_array(c1,ignore_hydrogen=False)
a2 = comparison_array(c2,ignore_hydrogen=False)

g = from_array(a1,a2)

print('MCS calculation: {}'.format(str(g.edge_count())))
```

Even though the MCS calculation now is 0 instead of 3 as I expected, I print these two graphs out based on the code you provided, and the result is as follows:

```
'temp_1.gexf'
0(N 1 0), 1(C 1 0), 2(N 0 0), 3(N 1 0), 4(N 0 0), 5(C 1 0), 6(N 1 0), 7(C 1 0), 8(C 1 0), 9(C 1 0), 10(C 1 0), 11(C 1 0)
0=1, 1-2, 1-3, 2-4, 2-5, 3=6, 4-6, 5=7, 5-8, 7-9, 8=10, 9=11, 10-11

'temp_2.gexf'
0(C 0 0), 1(C 1 0), 2(O 1 0), 3(S 0 0), 4(C 0 0), 5(C 1 0), 6(C 1 0)
0-1, 1=2, 1-3, 3-4, 4-5, 5=6
```

As I see, the print result is correct, so I am wondering the unexpected MCS result is caused by the two numbers behind the chemical atom (e.g. '1 0' in (C 1 0)), so my concerns are as follows:

1.  Could you please explain what the meaning of two numbers behind the chemical atom?
2. If I do not want to use these two numbers to differentiate the nodes, i.e. I hope to only differentiate the nodes based on the type of chemical atom (e.g. consider (C 1 0) and (C 0 0) as the same), what should I do?
3. If I want to calculate the exact MCS instead of the approximate one, what should I do? Will set diameter a large number like 10000 resolves the issue?
4. Are you finding the Maximum Common Edge Subgraph (MCES), or Maximum Common Induced Subgraph (MCIS)?

Thanks a lot.

**Comment by mojaie** [comment]
A1. Meaning of the molecular graph summary is as follows
- First line: list of atoms
  - atom index(atom symbol, number of pi electron, charge)
- Second line: list of bonds
  - atom1, bond order(1: -, 2: =, 3: #), atom2

A2. MCS-DR does not have custom matching rules yet. For now, simple atom type match as you mentioned can be done by setting bond.order of all bonds to 1.

A3. I recommend to use RDKit FMCS for exact MCS calculation. Note that MCS-DR is exact (not approximate) and deterministic but the definition of subgraph isomorphism is a bit different and a diameter restriction is added for some kind of practical uses. Diameter=10000 is enough for most of chemical graphs but the MCS-DR size is still smaller than MCS due to the reason written in the paper I introduced above.

A4. MCES if atoms are defined as nodes in the graph. This is same as MCIS of its line graph because Delta-Y exchange problem is avoided by the distance descriptor mentioned above.

Here are other limitations of MCS-DR.

```py
mol1 = smiles_to_compound("CCC=O")
mol2 = smiles_to_compound("CCCO")
arr1 = mcsdr.comparison_array(mol1)
arr2 = mcsdr.comparison_array(mol2)
result = mcsdr.from_array(arr1, arr2).edge_count()
```

The result will be 1. Common edge should have both same atom symbol and pi electrons at the both side of the bond. This matching rule may rather too strict so I'm going to offer some options soon.

```py
mol1 = smiles_to_compound("CCO")
mol2 = smiles_to_compound("CCC")
arr1 = mcsdr.comparison_array(mol1)
arr2 = mcsdr.comparison_array(mol2)
result = mcsdr.from_array(arr1, arr2).edge_count()
```

This will be 0, unfortunately.
You may find that minimum number of MCS-DR edges found in the algorithm is 2. This is also a limitation of the distance descriptor method. I will not fix it until some practical inconveniences are found.

These limitations are the reason why your example molecules resulted edge_count=0. 

If you have further questions, please make new issue topics or rename the title of this topic.

**Comment by nightlyjourney** [comment]
Thank you so much for your detailed answers, truly appreciated :)

**Comment by mojaie** [comment]
Thank you for changing the title and for your interest in this library again.
